# Generated by Django 5.2.5 on 2025-08-28 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_id', models.CharField(max_length=20)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('duration', models.DurationField()),
                ('status', models.CharField(choices=[('answered', 'Answered'), ('missed', 'Missed'), ('transferred', 'Transferred')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_records', to='users.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CallTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfer', to='ai_calls.callrecord')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferred_calls', to='users.userprofile')),
            ],
        ),
    ]
